### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by doubleUTF** [knownunown/tpl-c900-openwrt-install#10]
Does the OpenWRT version of the AC900 router support repeater mode? I do not see WDS bridging or repeater mode as an option with the stock firmware. I'd like to unlock the firmware but if it doesn't support it, then it might not be worth the trouble.

Also, couldn't you share the encryption keys in the prelude step assuming the official firmware is the same for all? This would prevent users from having to run complex commands on linux. 

Does `stock.bin` refer to the full name of the .bin file extracted from the compressed .zip?
`ArcherC900v1_un-up-ver1-0-0-P1[20161130-rel67783].bin`

Another also, the factory download link is formatted incorrectly
`https://static.tp-link.com/ArcherC900%28US%29_V1_161130.zip`
vs
`https://static.tp-link.com/ArcherC900(US)_V1_161130.zip`

**Comment by tnytown** [comment]
Hi!

> Does the OpenWRT version of the AC900 router support repeater mode?

On my hardware, WDS does not appear to be supported:

```
# iw phy phy0 interface add wds0 type wds
command failed: Not supported (-122)
```

(Maybe I need a specific driver? I don't know much about WDS.)

You can certainly still use it as a repeater. There are two wireless interfaces (2.4/5ghz).
If you use the 2.4ghz as backhaul (station mode), you can run 5ghz in AP mode and NAT. This will
result in suboptimal network topology. Alternatively, you can also look into mesh, which is supported

> Also, couldn't you share the encryption keys in the prelude step assuming the official firmware is the same for all?

I'm not comfortable with doing that

> Does stock.bin refer to the full name of the .bin file extracted from the compressed .zip?

Yes

**Comment by doubleUTF** [comment]
Thank you @tnytown
