### ISSUE TITLE
Cannot follow after Prelude-4.

### ISSUE THREAD

**Issue by ghost** [knownunown/tpl-c900-openwrt-install#2]
Hi,

I tried following your steps, but got stuck at Prelude 5.
"Copy .encryption_params.sample into .encryption_params. Paste the key and the IV you found into the appropriate places in .encryption_params."

Where is .encryption_params file? Did you mean to download the .encryption_params.sample file and rename it into .encryption_params.?

**Comment by tnytown** [comment]
Yeah, sorry, the wording there is less than optimal. You should rename .encryption_params.sample to .encryption_params :)
