### ISSUE TITLE
No connection after reboot!

### ISSUE THREAD

**Issue by IleanaAldama** [knownunown/tpl-c900-openwrt-install#6]
Hi, thanks for your guide.
I read carefully and made sure that I was getting the correct result for each step.
after writing the image with mtd and rebooting, I can see from my main router that the Archer is getting an ip!.
But I cannot login to it for installing luci, I tried ssh and telnet with not luck (Im getting  Connection refused message)

Any ideas?

**Comment by tnytown** [comment]
Are you using ssh or telnet?

**Comment by tnytown** [comment]
Try connecting your computer to a LAN port then SSHing from there. The router's SSH server isn't accessible to WAN (i.e. global internet) by default.

**Comment by IleanaAldama** [comment]
Yup, that was my mistake I was trying to ssh using the wan interface. connected the ether cable to the lan interface and it worked
