### ISSUE TITLE
scp does not on tp-link stock firmware

### ISSUE THREAD

**Issue by ninadpchaudhari** [knownunown/tpl-c900-openwrt-install#7]
Thank you for this! :heart: :heart: :heart:

Btw, seems the scp command fails! ( seems dropbear server on default image does not have scp ! )
<img width="731" alt="Screen Shot 2020-09-24 at 6 47 40 PM" src="https://user-images.githubusercontent.com/1305825/94209231-c82c0180-fe99-11ea-9d43-2a440a352cd0.png">

I used tftp to copy the file instead.
<img width="735" alt="Screen Shot 2020-09-24 at 7 02 17 PM" src="https://user-images.githubusercontent.com/1305825/94209229-c7936b00-fe99-11ea-8a77-6df7fb6560c6.png">

## used OSX. 10.15.5
- installed squashfs using homebrew 
- started the default tftp server on OSX. `sudo launchctl load -F /System/Library/LaunchDaemons/tftp.plist` [ check if it is running : `netstat -na |grep \*.69` ] ([Ref](https://rick.cogley.info/post/run-a-tftp-server-on-mac-osx/))
- Copy the openwrt---.bin file in `/private/tftpboot`. needs sudo.
- Was not able to "put" file from my OSX machine to the router using the put command. Instead used get command from the router. 

note: Do not use the [Squashfs-factory](https://openwrt.org/toh/tp-link/tp-link_archer_c2_ac900) in the device's wiki page!!! has to be `squashfs-sysupgrade.bin`

After everything was done, 
I just downloaded the regular sysupgrade image and did sysupgrade .
https://openwrt.org/toh/tp-link/tp-link_archer_c2_ac900 

Will make changes & propose a pull request as time permits :)

**Comment by tnytown** [comment]
You can also try `cat firmware.bin | ssh root@host 'cat >/tmp/firmware.bin'` -- not sure why scp doesn't exist anymore on stock, or if it even existed in the first place
